# Generated by Django 5.1 on 2024-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='alliess',
            new_name='allies',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='enemises',
            new_name='enemies',
        ),
        migrations.AlterField(
            model_name='card',
            name='debut',
            field=models.DateField(verbose_name='Год появления'),
        ),
    ]
