# Generated by Django 5.1 on 2024-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='photo_card',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
