# Generated by Django 5.1 on 2024-09-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_photo_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='photo_card',
            new_name='photo_profile',
        ),
    ]
