# Generated by Django 5.1 on 2024-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_photo_card_card_photo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
