# Generated by Django 5.1 on 2024-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_card_name_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hero_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
